// all persons
GET http://localhost:8080/api/persons
###
// one person
GET http://localhost:8080/api/persons/63848924cf2534b9d992db61
###
//invalid person
GET http://localhost:8080/api/persons/7
###
// valid Delete
DELETE http://localhost:8080/api/persons/63846824d1ca26386ca9189e
###
//invalid delete
DELETE http://localhost:8080/api/persons/7
###
//Valid POST
POST http://localhost:8080/api/persons
Content-Type: application/json 

{
    "name": "Minnie Mouse",
    "number": "12-34056"
}
###
//invalid POST (no number)
POST http://localhost:8080/api/persons
Content-Type: application/json

{
    "name": "Donald Duck"
}
###
//invalid POST (duplicate name)
POST http://localhost:8080/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas", 
    "number": "040-123456"
}
###
//invalid POST (name < 3
POST http://localhost:8080/api/persons
Content-Type: application/json

{
    "name": "fo",
    "number": "123141"
}
