// all persons
GET http://localhost:8080/api/persons
###
// one person
GET http://localhost:8080/api/persons/6382d2b05070e5a9434dfb1c
###
//invalid person
GET http://localhost:8080/api/persons/7
###
// valid Delete
DELETE http://localhost:8080/api/persons/2
###
//invalid delete
DELETE http://localhost:8080/api/persons/7
###
//Valid POST
POST http://localhost:8080/api/persons
Content-Type: application/json 

{
    "name": "Minnie Mouse",
    "number": "1234056"
}
###
//invalid POST (no number)
POST http://localhost:8080/api/persons
Content-Type: application/json

{
    "name": "Donald Duck"
}
###
//invalid POST (duplicate name)
POST http://localhost:8080/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas", 
    "number": "040-123456"
}
###
